version: 2.1

executors:
  base-executor:
    working_directory: ~/workdir
    docker:
      - image: circleci/python:3.7.3

jobs:
  build:
    executor: base-executor
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule init
      - run: git submodule update --recursive
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: buildpipenv-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            touch ./whl/torch-1.6.0a0+b31f58d-cp37-cp37m-linux_armv7l.whl
            touch ./whl/torchvision-0.7.0a0+78ed10c-cp37-cp37m-linux_armv7l.whl
            pipenv install --dev --skip-lock
      - save_cache:
          key: buildpipenv-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
  py-linter:
    executor: base-executor
    steps:
      - checkout
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: pylinter-v2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            touch ./whl/torch-1.6.0a0+b31f58d-cp37-cp37m-linux_armv7l.whl
            touch ./whl/torchvision-0.7.0a0+78ed10c-cp37-cp37m-linux_armv7l.whl
            pipenv install --dev --skip-lock
      - save_cache:
          key: pylinter-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Run python code linter
          command: |
            make check-format

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build
      - py-linter